set_property SRC_FILE_INFO {cfile:F:/Desktop/Github/FPGA/Test/Test.srcs/constrs_1/imports/Downloads/Arty-A7-100-Master.xdc rfile:../../../Test.srcs/constrs_1/imports/Downloads/Arty-A7-100-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { clk }]; #IO_L12P_T1_MRCC_35 Sch=gclk[100]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J5    IOSTANDARD LVCMOS33 } [get_ports { led }]; #IO_25_35 Sch=led[5]
